using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Roleplay.Shared
{
    public class VehicleModel
    {
        public VehicleModel(string dis, string mod, int pri) { displayName = dis; modelName = mod; price = pri; }
        public VehicleModel(string dis, string mod, int pri, string vehCat) { displayName = dis; modelName = mod; price = pri; vehicleCategory = vehCat; }
        public string displayName;
        public string modelName;
        public int price;
        public string vehicleCategory;
    }

    public static class VehicleStoreItems
    {
        public static Dictionary<string, List<VehicleModel>> StoreMenus = new Dictionary<string, List<VehicleModel>>()
        {
            ["VehicleStore"] = new List<VehicleModel>()
            {
                new VehicleModel("Blista Compact", "blista2", 20000, "Compacts"),
                new VehicleModel("Blista", "blista", 24000, "Compacts"),
                new VehicleModel("Brioso R/A", "brioso", 30000, "Compacts"),
                new VehicleModel("Dilettante", "dilettante", 25000, "Compacts"),
                new VehicleModel("Issi", "issi2", 18000, "Compacts"),
                new VehicleModel("Issi Retro", "issi3", 30000, "Compacts"),
                new VehicleModel("Panto", "panto", 14000, "Compacts"),
                new VehicleModel("Prairie", "prairie", 25000, "Compacts"),
                new VehicleModel("Rhapsody", "rhapsody", 24000, "Compacts"),
                new VehicleModel("Cheburek", "cheburek", 13000, "Classics"),
                new VehicleModel("Fagaloa", "fagaloa", 16000, "Classics"),
                new VehicleModel("Cognoscenti Cabrio", "cogcabrio", 65000, "Coupes"),
                new VehicleModel("Exemplar", "exemplar", 60000, "Coupes"),
                new VehicleModel("F620", "f620", 80000, "Coupes"),
                new VehicleModel("Felon GT", "felon2", 65000, "Coupes"),
                new VehicleModel("Felon", "felon", 60000, "Coupes"),
                new VehicleModel("Jackal", "jackal", 60000, "Coupes"),
                new VehicleModel("Oracle XS", "oracle2", 66000, "Coupes"),
                new VehicleModel("Oracle", "oracle", 63000, "Coupes"),
                new VehicleModel("Sentinel XS", "sentinel2", 65000, "Coupes"),
                new VehicleModel("Sentinel", "sentinel", 60000, "Coupes"),
                new VehicleModel("Windsor Drop", "windsor2", 140000, "Coupes"),
                new VehicleModel("Windsor", "windsor", 120000, "Coupes"),
                new VehicleModel("Zion Cabrio", "zion2", 55000, "Coupes"),
                new VehicleModel("Zion", "zion", 50000, "Coupes"),
                new VehicleModel("Blade", "blade", 20000, "Muscle"),
                new VehicleModel("Buccaneer", "buccaneer", 29000, "Muscle"),
                new VehicleModel("Chino", "chino", 32000, "Muscle"),
                new VehicleModel("Chino 2", "chino2", 63000, "Muscle"),
                new VehicleModel("Dominator", "dominator", 50000, "Muscle"),
                new VehicleModel("Dominator GTX", "dominator3", 75000, "Muscle"),
                new VehicleModel("Dukes", "dukes", 50000, "Muscle"),
                new VehicleModel("Ellie", "ellie", 65000, "Muscle"),
                new VehicleModel("Faction", "faction", 20000, "Muscle"),
                new VehicleModel("Faction Custom", "faction2", 29000, "Muscle"),
                new VehicleModel("Faction Custom 2", "faction3", 60000, "Muscle"),
                new VehicleModel("Gauntlet", "gauntlet", 40000, "Muscle"),
                new VehicleModel("Hotknife", "hotknife", 70000, "Muscle"),
                new VehicleModel("Hermes", "hermes", 43000, "Muscle"),
                new VehicleModel("Hustler", "hustler", 80000, "Muscle"),
                new VehicleModel("Lurcher", "lurcher", 50000, "Muscle"),
                new VehicleModel("Nightshade", "nightshade", 75000, "Muscle"),
                new VehicleModel("Phoenix", "phoenix", 69000, "Muscle"),
                new VehicleModel("Picador", "picador", 12000, "Muscle"),
                new VehicleModel("Rat-Loader", "ratloader", 29000, "Muscle"),
                new VehicleModel("Rat-Truck", "ratloader2", 40000, "Muscle"),
                new VehicleModel("Rapid GT Classic", "rapidgt3", 70000, "Muscle"),
                new VehicleModel("Ruiner", "ruiner", 15000, "Muscle"),
                new VehicleModel("Sabre Turbo", "sabregt", 25000, "Muscle"),
                new VehicleModel("Sabre Custom", "sabregt2", 40000, "Muscle"),
                new VehicleModel("Slamvan", "slamvan", 40000, "Muscle"),
                new VehicleModel("Slamvan Lost", "slamvan2", 50000, "Muscle"),
                new VehicleModel("Slamvan Custom", "slamvan3", 50000, "Muscle"),
                new VehicleModel("Stalion", "stalion", 60000, "Muscle"),
                new VehicleModel("Tampa", "tampa", 70000, "Muscle"),
                new VehicleModel("Tampa 2", "tampa2", 160000, "Muscle"),
                new VehicleModel("Vigero", "vigero", 35000, "Muscle"),
                new VehicleModel("Virgo", "virgo", 30000, "Muscle"),
                new VehicleModel("Voodoo", "voodoo", 60000, "Muscle"),
                new VehicleModel("Yosemite", "yosemite", 70000, "Muscle"),
                new VehicleModel("BJ Injection", "bfinjection", 16000, "Off-Road"),
                new VehicleModel("Bifta", "bifta", 25000, "Off-Road"),
                new VehicleModel("Blazer", "blazer", 8000, "Off-Road"),
                new VehicleModel("Blazer Flame", "blazer3", 10000, "Off-Road"),
                new VehicleModel("Bodhi", "bodhi2", 20000, "Off-Road"),
                new VehicleModel("Brawler", "brawler", 95000, "Off-Road"),
                new VehicleModel("Dloader", "dloader", 30000, "Off-Road"),
                new VehicleModel("Dune", "dune", 13000, "Off-Road"),
                new VehicleModel("Dubsta 6x6", "dubsta3", 180000, "Off-Road"),
                new VehicleModel("Guardian", "guardian", 45000, "Off-Road"),
                new VehicleModel("Kalahari", "kalahari", 30000, "Off-Road"),
                new VehicleModel("Kamacho", "kamacho", 70000, "Off-Road"),
                new VehicleModel("Rancher XL", "rancherxl", 15000, "Off-Road"),
                new VehicleModel("Rebel", "rebel", 15000, "Off-Road"),
                new VehicleModel("Rebel 2", "rebel2", 40000, "Off-Road"),
                new VehicleModel("Riata", "riata", 60000, "Off-Road"),
                new VehicleModel("Sandking", "sandking", 60000, "Off-Road"),
                new VehicleModel("Sandking 2", "sandking2", 57000, "Off-Road"),
                new VehicleModel("Streiter", "streiter", 75000, "Off-Road"),
                new VehicleModel("Trophy Truck", "trophytruck", 85000, "Off-Road"),
                new VehicleModel("Asea", "asea", 12000, "Sedans"),
                new VehicleModel("Cog55", "cog55", 75000, "Sedans"),
                new VehicleModel("Cognoscenti", "cognoscenti", 70000, "Sedans"),
                new VehicleModel("Cheburek", "cheburek", 45000, "Sedans"),
                new VehicleModel("Emperor", "emperor", 10000, "Sedans"),
                new VehicleModel("Emperor 2", "emperor2", 15000, "Sedans"),
                new VehicleModel("Fugitive", "fugitive", 24000, "Sedans"),
                new VehicleModel("Fagaloa", "fagaloa", 35000, "Sedans"),
                new VehicleModel("Glendale", "glendale", 20000, "Sedans"),
                new VehicleModel("Ingot", "ingot", 10000, "Sedans"),
                new VehicleModel("Intruder", "intruder", 25000, "Sedans"),
                new VehicleModel("Premier", "premier", 15000, "Sedans"),
                new VehicleModel("Primo", "primo", 10000, "Sedans"),
                new VehicleModel("Primo Custom", "primo2", 35000, "Sedans"),
                new VehicleModel("Regina", "regina", 14000, "Sedans"),
                new VehicleModel("Romero", "romero", 40000, "Sedans"),
                new VehicleModel("Stanier", "stanier", 12000, "Sedans"),
                new VehicleModel("Stratum", "stratum", 13000, "Sedans"),
                new VehicleModel("Stretch", "stretch", 48000, "Sedans"),
                new VehicleModel("Surge", "surge", 40000, "Sedans"),
                new VehicleModel("Tailgater", "tailgater", 60000, "Sedans"),
                new VehicleModel("Warrener", "warrener", 40000, "Sedans"),
                new VehicleModel("Washington", "washington", 15000, "Sedans"),
                new VehicleModel("9F Cabrio", "ninef2", 180000, "Sports"),
                new VehicleModel("9F", "ninef", 170000, "Sports"),
                new VehicleModel("Alpha", "alpha", 160000, "Sports"),
                new VehicleModel("Banshee", "banshee", 170000, "Sports"),
                new VehicleModel("Bestia GTS", "bestiagts", 175000, "Sports"),
                new VehicleModel("Buffalo", "buffalo", 40000, "Sports"),
                new VehicleModel("Buffalo S", "buffalo2", 70000, "Sports"),
                new VehicleModel("Carbonizzare", "carbonizzare", 175000, "Sports"),
                new VehicleModel("Comet", "comet2", 170000, "Sports"),
                new VehicleModel("Comet SR", "comet5", 195000, "Sports"),
                new VehicleModel("Coquette", "coquette", 150000, "Sports"),
                new VehicleModel("Feltzer", "feltzer2", 145000, "Sports"),
                new VehicleModel("Furore GT", "furoregt", 110000, "Sports"),
                new VehicleModel("Fusilade", "fusilade", 60000, "Sports"),
                new VehicleModel("Flash GT", "flashgt", 100000, "Sports"),
                new VehicleModel("Futo", "futo", 50000, "Sports"),
                new VehicleModel("GB200", "gb200", 80000, "Sports"),
                new VehicleModel("Jester", "jester", 130000, "Sports"),
                new VehicleModel("Jester Retro", "jester3", 150000, "Sports"),
                new VehicleModel("Hotring", "hotring", 200000, "Sports"),
                new VehicleModel("Khamelion", "KHAMELION", 110000, "Sports"),
                new VehicleModel("Kuruma", "kuruma", 80000, "Sports"),
                new VehicleModel("Lynx", "lynx", 155000, "Sports"),
                new VehicleModel("Massacro (Racecar)", "massacro2", 180000, "Sports"),
                new VehicleModel("Massacro", "massacro", 170000, "Sports"),
                new VehicleModel("Neon", "neon", 100000, "Sports"),
                new VehicleModel("Omnis", "omnis", 120000, "Sports"),
                new VehicleModel("Penumbra", "penumbra", 50000, "Sports"),
                new VehicleModel("Rapid GT", "rapidgt", 135000, "Sports"),
                new VehicleModel("Raiden", "raiden", 103000, "Sports"),
                new VehicleModel("Raptor", "RAPTOR", 75000, "Sports"),
                new VehicleModel("Ruston", "RUSTON", 80000, "Sports"),
                new VehicleModel("Pariah", "pariah", 190000, "Sports"),
                new VehicleModel("Schwarzer", "Schwarzer", 80000, "Sports"),
                new VehicleModel("Seven-70", "SEVEN70", 198000, "Sports"),
                new VehicleModel("Sultan", "sultan", 25000, "Sports"),
                new VehicleModel("Surano", "surano", 97000, "Sports"),
                new VehicleModel("Sentinel Classic", "sentinel3", 75000, "Sports"),
                new VehicleModel("Tropos", "tropos", 125000, "Sports"),
                new VehicleModel("Verkierer", "verlierer2", 123000, "Sports"),
                new VehicleModel("GT-R", "gtr", 150000, "Sports"),
                new VehicleModel("190z", "z190", 125000, "Sports Classics"),
                new VehicleModel("Casco", "casco", 110000, "Sports Classics"),
                new VehicleModel("Cheetah Classic", "cheetah2", 125000, "Sports Classics"),
                new VehicleModel("Coquette Classic", "coquette2", 93000, "Sports Classics"),
                new VehicleModel("Coquette Blackfin", "coquette3", 80000, "Sports Classics"),
                new VehicleModel("Mamba", "mamba", 120000, "Sports Classics"),
                new VehicleModel("Manana", "manana", 25000, "Sports Classics"),
                new VehicleModel("Monroe", "monroe", 175000, "Sports Classics"),
                new VehicleModel("Michelli GT", "michelli", 98000, "Sports Classics"),
                new VehicleModel("Peyote", "peyote", 60000, "Sports Classics"),
                new VehicleModel("Infernus Classic", "infernus2", 135000, "Sports Classics"),
                new VehicleModel("Pigalle", "pigalle", 65000, "Sports Classics"),
                new VehicleModel("Stinger", "stinger", 117000, "Sports Classics"),
                new VehicleModel("Retinue", "retinue", 96000, "Sports Classics"),
                new VehicleModel("GT500", "gt500", 105000, "Sports Classics"),
                new VehicleModel("Toreno", "torero", 150000, "Sports Classics"),
                new VehicleModel("Tornado 2", "tornado2", 50000, "Sports Classics"),
                new VehicleModel("Tornado 3", "tornado3", 20000, "Sports Classics"),
                new VehicleModel("Tornado 4", "tornado4", 25000, "Sports Classics"),
                new VehicleModel("Tornado 5", "tornado5", 78000, "Sports Classics"),
                new VehicleModel("Turismo Classic", "turismo2", 105000, "Sports Classics"),
                new VehicleModel("Autarch", "autarch", 380000, "Super"),
                new VehicleModel("Adder", "adder", 370000, "Super"),
                new VehicleModel("Banshee 900r", "banshee2", 425000, "Super"),
                new VehicleModel("Bullet", "bullet", 355000, "Super"),
                new VehicleModel("Cheetah", "cheetah", 280000, "Super"),
                new VehicleModel("ETR1", "sheava", 400000, "Super"),
                new VehicleModel("Entity XXR", "entity2", 385000, "Super"),
                new VehicleModel("Infernus", "infernus", 367000, "Super"),
                new VehicleModel("Italigtb", "italigtb", 370000, "Super"),
                new VehicleModel("Italigtb2", "italigtb2", 378000, "Super"),
                new VehicleModel("Nero", "nero", 380000, "Super"),
                new VehicleModel("Osiris", "osiris", 400000, "Super"),
                new VehicleModel("Penetrator", "penetrator", 390000, "Super"),
                new VehicleModel("Pfister811", "pfister811", 410000, "Super"),
                new VehicleModel("RE-7B", "le7b", 398000, "Super"),
                new VehicleModel("Reaper", "reaper", 387000, "Super"),
                new VehicleModel("Sultan RS", "sultanrs", 140000, "Super"),
                new VehicleModel("Specter", "specter", 210000, "Super"),
                new VehicleModel("SC1", "sc1", 650000, "Super"),
                new VehicleModel("T20", "t20", 380000, "Super"),
                new VehicleModel("Taipan", "taipan", 370000, "Super"),
                new VehicleModel("Tempesta", "tempesta", 360000, "Super"),
                new VehicleModel("Turismo R", "turismor", 390000, "Super"),
                new VehicleModel("Tyrus", "tyrus", 365000, "Super"),
                new VehicleModel("Tyrant", "tyrant", 385000, "Super"),
                new VehicleModel("Vacca", "vacca", 320000, "Super"),
                new VehicleModel("Vagner", "vagner", 400000, "Super"),
                new VehicleModel("Voltic", "voltic", 180000, "Super"),
                new VehicleModel("Visione", "visione", 389000, "Super"),
                new VehicleModel("X80 Proto", "prototipo", 1500000, "Super"),
                new VehicleModel("Tezeract", "tezeract", 400000, "Super"),
                new VehicleModel("XA21", "xa21", 370000, "Super"),
                new VehicleModel("Zentorno", "zentorno", 375000, "Super"),
                new VehicleModel("Baller", "baller", 50000, "SUVs"),
                new VehicleModel("BJXL", "bjxl", 35000, "SUVs"),
                new VehicleModel("Cavalcade", "cavalcade", 60000, "SUVs"),
                new VehicleModel("Contender", "contender", 80000, "SUVs"),
                new VehicleModel("Dubsta", "dubsta", 90000, "SUVs"),
                new VehicleModel("FQ2", "fq2", 50000, "SUVs"),
                new VehicleModel("Granger", "granger", 35000, "SUVs"),
                new VehicleModel("Gresley", "gresley", 29000, "SUVs"),
                new VehicleModel("Habanero", "habanero", 42000, "SUVs"),
                new VehicleModel("Huntley", "huntley", 60000, "SUVs"),
                new VehicleModel("Landstalker", "landstalker", 48000, "SUVs"),
                new VehicleModel("Mesa 2", "mesa3", 75000, "SUVs"),
                new VehicleModel("Mesa", "mesa", 35000, "SUVs"),
                new VehicleModel("Patriot", "patriot", 50000, "SUVs"),
                new VehicleModel("Radius", "radi", 32000, "SUVs"),
                new VehicleModel("Rocoto", "rocoto", 63000, "SUVs"),
                new VehicleModel("Seminole", "seminole", 35000, "SUVs"),
                new VehicleModel("Serrano", "serrano", 50000, "SUVs"),
                new VehicleModel("XLS", "xls", 75000, "SUVs"),
                new VehicleModel("Bison", "bison", 30000, "Vans"),
                new VehicleModel("Bobcat XL", "bobcatxl", 23000, "Vans"),
                new VehicleModel("Boxville", "boxville", 26000, "Vans"),
                new VehicleModel("Burrito", "burrito", 25000, "Vans"),
                new VehicleModel("Minivan", "minivan", 20000, "Vans"),
                new VehicleModel("Moonbeam", "moonbeam", 22000, "Vans"),
                new VehicleModel("Paradise", "paradise", 25000, "Vans"),
                new VehicleModel("Pony", "pony", 20000, "Vans"),
                new VehicleModel("Rumpo", "rumpo", 13000, "Vans"),
                new VehicleModel("Speedo", "speedo", 14000, "Vans"),
                new VehicleModel("Surfer", "surfer", 20000, "Vans"),
                new VehicleModel("Youga", "youga", 16000, "Vans"),
                new VehicleModel("Baller2", "Baller2", 70000, "SUVs"),
                new VehicleModel("Baller3", "Baller3", 85000, "SUVs"),
                new VehicleModel("Baller4", "Baller4", 80000, "SUVs"),
                new VehicleModel("Dubsta2", "dubsta2", 109000, "SUVs"),
                new VehicleModel("Toros", "toros", 109000, "SUVs"),
                new VehicleModel("Deviant", "deviant", 70000, "Muscle"),
                new VehicleModel("Tulip", "tulip", 80000, "Muscle"),
                new VehicleModel("Vamos", "vamos", 75000, "Muscle"),
                new VehicleModel("Impaler", "impaler", 31000, "Muscle"),
                new VehicleModel("Clique", "clique", 9000, "Muscle"),
                new VehicleModel("Buccaneer2", "buccaneer2", 60000, "Muscle"),
                new VehicleModel("Virgo2", "virgo2", 65000, "Muscle"),
                new VehicleModel("Virgo3", "virgo3", 80000, "Muscle"),
                new VehicleModel("Voodoo2", "voodoo2", 12000, "Muscle"),
                new VehicleModel("Btype2", "btype2", 170000, "Sports Classics"),
                new VehicleModel("Btype3", "Btype3", 150000, "Sports Classics"),
                new VehicleModel("Feltzer3", "feltzer3", 89000, "Sports Classics"),
                new VehicleModel("Savestra", "savestra", 109000, "Sports Classics"),
                new VehicleModel("Swinger", "swinger", 160000, "Sports Classics"),
                new VehicleModel("Elegy2", "Elegy2", 140000, "Sports"),
                new VehicleModel("Revolter", "revolter", 120000, "Sports"),
                new VehicleModel("Schlagen", "schlagen", 200000, "Sports"),
                new VehicleModel("Cyclone", "cyclone", 345000, "Super"),
                new VehicleModel("Deveste", "deveste", 440000, "Super"),
                new VehicleModel("FMJ", "fmj", 384000, "Super"),
                new VehicleModel("GP1", "gp1", 350000, "Super"),
                new VehicleModel("BLAZER4", "blazer4", 25000, "Off-Road"),
                new VehicleModel("FREECRAWLER", "freecrawler", 80000, "Off-Road"),
                new VehicleModel("Trophytruck2", "trophytruck2", 100000, "Off-Road"),
                new VehicleModel("Bison2", "bison2", 26000, "Vans"),
                new VehicleModel("Bison3", "bison3", 26000, "Vans"),
                new VehicleModel("Burrito2", "burrito2", 25000, "Vans"),
                new VehicleModel("Burrito3", "burrito3", 25000, "Vans"),
                new VehicleModel("Burrito4", "burrito4", 25000, "Vans"),
                new VehicleModel("GBURRITO", "gburrito", 30000, "Vans"),
                new VehicleModel("GBURRITO2", "gburrito2", 30000, "Vans"),
                new VehicleModel("Minivan2", "minivan2", 30000, "Vans"),
                new VehicleModel("Rumpo2", "rumpo2", 13000, "Vans"),
                new VehicleModel("Rumpo3", "rumpo3", 55000, "Vans"),
                new VehicleModel("Speedo2", "speedo2", 20000, "Vans"),
                new VehicleModel("Surfer2", "surfer2", 14000, "Vans"),
                new VehicleModel("Youga2", "youga2", 30000, "Vans"),
                new VehicleModel("MOONBEAM2", "moonbeam2", 32000, "Vans"),
                new VehicleModel("Peyote", "Peyote", 105000, "Sports Classics"),

                //New Casino DLC
                new VehicleModel("Paragon", "Paragon", 100000, "Sports"),
                new VehicleModel("Jugular", "Jugular", 100000, "Sports"),
                new VehicleModel("asbo", "asbo", 20000, "Sports"),
                new VehicleModel("caracara2", "caracara2", 80000, "Off-Road"),
                new VehicleModel("drafter", "drafter", 130000, "Sports"),
                new VehicleModel("everon", "everon", 85000, "Off-Road"),
                new VehicleModel("Gauntlet3", "Gauntlet3", 105000, "Sports Classics"),
                new VehicleModel("Gauntlet4", "Gauntlet4", 150000, "Sports"),
                new VehicleModel("Locust", "Locust", 90000, "Sports"),
                new VehicleModel("kanjo", "kanjo", 45000, "Sports"),
                new VehicleModel("komoda", "komoda", 95000, "Sports"),
                new VehicleModel("Novak", "Novak", 35000, "SUVs"),
                new VehicleModel("outlaw", "outlaw", 75000, "Off-Road"),
                new VehicleModel("Sugoi", "Sugoi", 95000, "Sports"),
                new VehicleModel("sultan2", "sultan2", 150000, "Sports Classics"),
                new VehicleModel("Thrax", "Thrax", 300000, "Super"),
                new VehicleModel("vstr", "vstr", 105000, "Sports"),
                new VehicleModel("yosemite2", "yosemite2", 105000, "Off-Road"),

                //New Custom Vehicles
                new VehicleModel("gmcciv", "gmcciv", 50000, "Off-Road"),
                new VehicleModel("16challenger", "16challenger", 55000, "Sports"),
                new VehicleModel("camaro_ss", "camaro_ss", 90000, "Sports Classics"),
                new VehicleModel("chevelle1970", "chevelle1970", 90000, "Sports Classics"),
                new VehicleModel("crownvic", "crownvic", 50000, "Sedans"),
                new VehicleModel("camry55", "camry55", 50000, "Sedans"),
                new VehicleModel("expedition", "expedition", 65000, "SUVs"),
                new VehicleModel("velar", "velar", 85000, "SUVs"),
                new VehicleModel("gmt400", "gmt400", 55000, "SUVs"),
                new VehicleModel("tahoe", "tahoe", 55000, "SUVs"),
                new VehicleModel("Mustang", "rmodmustang", 55000, "Sports"),
                new VehicleModel("hellcat", "hellcat", 55000, "Sports"),
                new VehicleModel("ghis2", "ghis2", 300000, "Super"),

                //Bikes
                new VehicleModel("Fixter", "fixter", 500, "Bicycles"),
                new VehicleModel("Scorcher", "scorcher", 450, "Bicycles"),
                new VehicleModel("Cruiser", "cruiser", 200, "Bicycles"),
                new VehicleModel("BMX", "bmx", 400, "Bicycles"),
                new VehicleModel("Triathlon bike 1", "tribike", 1000, "Bicycles"),
                new VehicleModel("Triathlon bike 2", "tribike2", 1000, "Bicycles"),
                new VehicleModel("Triathlon bike 3", "tribike3", 1000, "Bicycles"),
            },
            ["MotorcycleStore"] = new List<VehicleModel>()
            {
                new VehicleModel("Akuma", "akuma", 30000, "Motorcycles"),
                new VehicleModel("Avarus", "avarus", 35000, "Motorcycles"),
                new VehicleModel("Bagger", "bagger", 28000, "Motorcycles"),
                new VehicleModel("Bati 801", "bati", 38000, "Motorcycles"),
                new VehicleModel("Bati 801RR", "bati2", 40000, "Motorcycles"),
                new VehicleModel("BF400", "bf400", 29000, "Motorcycles"),
                new VehicleModel("Carbon RS", "carbonrs", 37500, "Motorcycles"),
                new VehicleModel("Chimera", "chimera", 33000, "Motorcycles"),
                new VehicleModel("Cliffhanger", "cliffhanger", 31000, "Motorcycles"),
                new VehicleModel("Daemon", "daemon", 40000, "Motorcycles"),
                new VehicleModel("Defiler", "defiler", 38000, "Motorcycles"),
                new VehicleModel("Diablous Custom", "diablous2", 40000, "Motorcycles"),
                new VehicleModel("Diablous", "diablous", 43000, "Motorcycles"),
                new VehicleModel("Double T", "double", 37000, "Motorcycles"),
                new VehicleModel("Enduro", "enduro", 12000, "Motorcycles"),
                new VehicleModel("Esskey", "esskey", 20000, "Motorcycles"),
                new VehicleModel("Faggio 2", "faggio2", 9000, "Motorcycles"),
                new VehicleModel("Faggio 3", "faggio3", 8400, "Motorcycles"),
                new VehicleModel("Faggio", "faggio", 7500, "Motorcycles"),
                new VehicleModel("FCR Custom", "fcr2", 31000, "Motorcycles"),
                new VehicleModel("FCR", "fcr", 28000, "Motorcycles"),
                new VehicleModel("Gargoyle", "gargoyle", 22000, "Motorcycles"),
                new VehicleModel("Hakuchou Drag", "hakuchou2", 35000, "Motorcycles"),
                new VehicleModel("Hakuchou", "hakuchou", 35000, "Motorcycles"),
                new VehicleModel("Hexer", "hexer", 28000, "Motorcycles"),
                new VehicleModel("Innovation", "innovation", 26000, "Motorcycles"),
                new VehicleModel("Lectro", "lectro", 32000, "Motorcycles"),
                new VehicleModel("Manchez", "manchez", 25000, "Motorcycles"),
                new VehicleModel("Nemesis", "nemesis", 28000, "Motorcycles"),
                new VehicleModel("Nightblade", "nightblade", 26000, "Motorcycles"),
                new VehicleModel("PCJ 675", "pcj", 20000, "Motorcycles"),
                new VehicleModel("Ratbike", "ratbike", 19000, "Motorcycles"),
                new VehicleModel("Ruffian", "ruffian", 23000, "Motorcycles"),
                new VehicleModel("Sanchez", "sanchez", 23000, "Motorcycles"),
                new VehicleModel("Sanctus", "sanctus", 48000, "Motorcycles"),
                new VehicleModel("Sovereign", "sovereign", 36000, "Motorcycles"),
                new VehicleModel("Thrust", "thrust", 20000, "Motorcycles"),
                new VehicleModel("Vader", "vader", 30000, "Motorcycles"),
                new VehicleModel("Vindicator", "vindicator", 28000, "Motorcycles"),
                new VehicleModel("Vortex", "vortex", 37000, "Motorcycles"),
                new VehicleModel("Wolfsbane", "wolfsbane", 28000, "Motorcycles"),
                new VehicleModel("Zombie A", "zombiea", 32000, "Motorcycles"),
                new VehicleModel("Zombie B", "zombieb", 30000, "Motorcycles"),
                new VehicleModel("Daemon2", "Daemon2", 50000, "Motorcycles"),
                new VehicleModel("Rrocket", "Rrocket", 50000, "Motorcycles"),
            },
            ["UtilityStore"] = new List<VehicleModel>()
            {
                new VehicleModel("Caddy", "caddy", 5500, "Small"),
                new VehicleModel("Caddy 2", "caddy2", 2000, "Small"),
                new VehicleModel("Caddy 3", "caddy3", 3500, "Small"),
                new VehicleModel("Forklift", "forklift", 9000, "Small"),
                new VehicleModel("Lawnmower", "mower", 4000, "Small"),
                new VehicleModel("Camper", "camper", 12000, "Vans"),
                new VehicleModel("Journey", "journey", 15000, "Vans"),
                new VehicleModel("Scrap Truck", "SCRAP", 15000, "Utility"),
                new VehicleModel("Tractor (Fieldmaster)", "tractor2", 9000, "Utility"),
                new VehicleModel("Tractor (Vintage)", "tractor", 3300, "Utility"),
                new VehicleModel("Tow Truck", "towtruck", 23000, "Utility"),
                new VehicleModel("Tow Truck 2", "towtruck2", 17800, "Utility"),
                new VehicleModel("Tour Bus", "tourbus", 17000, "Utility"),
                new VehicleModel("Hauler", "hauler", 25000, "Commercial"),
                new VehicleModel("Packer", "packer", 35000, "Commercial"),
                new VehicleModel("Phantom", "phantom", 35000, "Commercial"),
                new VehicleModel("Taco", "taco", 55000, "Commercial"),
                new VehicleModel("flatbed", "flatbed", 50000, "Commercial"),
            },
            ["TunerStore"] = new List<VehicleModel>()
            {
                new VehicleModel("Comet Retro", "comet3", 200000, "Tuners"),
                new VehicleModel("Elegy Retro", "elegy", 100000, "Tuners"),
            },
            ["BoatStore"] = new List<VehicleModel>()
            {
                new VehicleModel("speeder", "speeder", 50000, "Speed Boats"),
                new VehicleModel("speeder2", "speeder2", 40000, "Speed Boats"),
                new VehicleModel("toro", "toro", 40000, "Speed Boats"),
                new VehicleModel("suntrap", "suntrap", 45000, "Motor Boats"),
                new VehicleModel("tropic", "tropic", 45000, "Motor Boats"),
                new VehicleModel("squalo", "squalo", 45000, "Motor Boats"),
                new VehicleModel("jetmax", "jetmax", 45000, "Motor Boats"),
                new VehicleModel("dinghy", "dinghy", 35000, "Rib Boats"),
                new VehicleModel("dinghy2", "dinghy2", 35000, "Rib Boats"),
                new VehicleModel("dinghy4", "dinghy4", 35000, "Rib Boats"),
                new VehicleModel("seashark", "seashark", 10000, "Jetskis"),
                new VehicleModel("seashark2", "seashark2", 10000, "Jetskis"),
            },
        };
    }
}